# Generated by Django 2.0.4 on 2018-04-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('surname_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=200)),
            ],
        ),
    ]
