# Generated by Django 2.0.4 on 2018-04-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hierarchy', '0002_person_tasks_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='tasks_ids',
            new_name='task_ids',
        ),
    ]
