# Generated by Django 2.0.4 on 2018-04-11 13:57

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Hierarchy', '0004_person_subordinate_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='surname_name',
            new_name='surname',
        ),
        migrations.AlterField(
            model_name='person',
            name='subordinate_ids',
            field=models.CharField(default='', editable=False, max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='task_ids',
            field=models.CharField(default='', editable=False, max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
