# Generated by Django 2.0.4 on 2018-04-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hierarchy', '0005_auto_20180411_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='subordinate_ids',
        ),
        migrations.RemoveField(
            model_name='person',
            name='task_ids',
        ),
    ]
