# Generated by Django 2.0.4 on 2018-04-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180414_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(choices=[('BOS', 'Boss'), ('MAN', 'Manager'), ('SUP', 'Supervisor'), ('WOR', 'Worker')], default='Worker', max_length=3),
        ),
    ]
